/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tp_xmaihh_trainingthings_jni_uninstall_http_utils_JNILoader */

#ifndef _Included_tp_xmaihh_trainingthings_jni_uninstall_http_utils_JNILoader
#define _Included_tp_xmaihh_trainingthings_jni_uninstall_http_utils_JNILoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tp_xmaihh_trainingthings_jni_uninstall_http_utils_JNILoader
 * Method:    uninstall
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_tp_xmaihh_trainingthings_jni_1uninstall_1http_utils_JNILoader_uninstall
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jint);

/*
 * Class:     tp_xmaihh_trainingthings_jni_uninstall_http_utils_JNILoader
 * Method:    httpConnect
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_tp_xmaihh_trainingthings_jni_1uninstall_1http_utils_JNILoader_httpConnect
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
