/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_sysproperties_GetProperties */

#ifndef _Included_com_android_sysproperties_GetProperties
#define _Included_com_android_sysproperties_GetProperties
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_sysproperties_GetProperties
 * Method:    native_get
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_android_sysproperties_GetProperties_native_1get__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_android_sysproperties_GetProperties
 * Method:    native_get
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_android_sysproperties_GetProperties_native_1get__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
