/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <sys/system_properties.h>
#include <android/log.h>

#define LOGI(...) __android_log_print(ANDROID_LOG_INFO,"",__VA_ARGS__)

extern "C" JNIEXPORT jstring JNICALL
Java_com_android_sysproperties_GetProperties_native_1get__Ljava_lang_String_2
        (JNIEnv *env, jclass clazz, jstring keyJ, jstring defJ) {
    int len;
    const char *key;
    char buf[100];
    jstring rvJ = NULL;

    if (keyJ == NULL) {
        LOGI("key must not be null.");
        goto error;
    }

    key = env->GetStringUTFChars(keyJ, NULL);

    len = __system_property_get(key, buf);
    if ((len <= 0) && (defJ != NULL)) {
        rvJ = defJ;
    } else if (len >= 0) {
        rvJ = env->NewStringUTF(buf);
    } else {
        rvJ = env->NewStringUTF("");
    }


    error:
    env->ReleaseStringUTFChars(keyJ, key);
    return rvJ;
}


extern "C" JNIEXPORT jstring JNICALL
Java_com_android_sysproperties_GetProperties_native_1get__Ljava_lang_String_2Ljava_lang_String_2
        (JNIEnv *env, jclass clazz, jstring keyJ) {
    return Java_com_android_sysproperties_GetProperties_native_1get__Ljava_lang_String_2(
            env, clazz, keyJ, NULL);
}

